#pragma once

enum class STAGE_TYPE	{	STAGE_START, STAGE_SELECT, STAGE_QUIT, STAGE_VILLAGE, STAGE_DUNGEON, STAGE_GATE, STAGE_BOSS, STAGE_LOAD, STAGE_END	};

enum class BTN_EVENT	{	BTN_NOEVENT, BTN_HOVER, BTN_ONCLICK, BTN_END									};
enum class BTN_TAG		{	BTN_START, BTN_SETTING, BTN_RECORD, BTN_STAFF, BTN_EXIT, BTN_ENTERSTAGE, BTN_BACK, BTN_YES, BTN_NO, BTN_END	};

enum class OBJECT_TAG	{	OBJ_MONSTER, OBJ_MONSTER_HITBOX, OBJ_NPC, OBJ_PORTAL, OBJ_ENVIROMENT, OBJ_FLOWER, OBJ_BOSS, OBJ_BOSS_HITBOX, OBJ_BOSS_HITBOX_CIRCLE, OBJ_PLAYER,
							OBJ_PLAYER_HITBOX, OBJ_FRONT_ENVIROMENT, OBJ_UI, OBJ_END};

enum class PLAYER_MOVE_STATE	{ PLAYER_IDLE_R, PLAYER_IDLE_L,	PLAYER_RUN_R, PLAYER_RUN_L,	PLAYER_TURN_RTL, PLAYER_TURN_LTR,	PLAYER_NONE};
enum class PLAYER_JUMP_STATE	{	PLAYER_JUMP_R, PLAYER_JUMP_L,	PLAYER_DOUBLE_JUMP_R, PLAYER_DOUBLE_JUMP_L, 
									PLAYER_FALL_R,  PLAYER_FALL_L, PLAYER_SLOW_FALL_R, PLAYER_SLOW_FALL_L,						
									PLAYER_PARACHUTE_L, PLAYER_PARACHUTE_R,	PLAYER_NONE};
enum class PLAYER_ATTACK_STATE	{ PLAYER_ATTACK_R, PLAYER_ATTACK_L,																PLAYER_NONE};
enum class PLAYER_SKILL_STATE	{PLAYER_DASH_L, PLAYER_DASH_R, PLAYER_THREAD_R, PLAYER_THREAD_L, PLAYER_HEAL_L, PLAYER_HEAL_R, 
								 PLAYER_THROW_R, PLAYER_THROW_L, PLAYER_NONE };
enum class PLAYER_DEFAULT_STATE { PLAYER_DAMAGED_R, PLAYER_DAMAGED_L, PLAYER_INFINITY, PLAYER_DEAD,  PLAYER_NONE};

enum class NPC_TAG		{	NPC_BIGPULP, NPC_BIGBUG, NPC_GHOUL, NPC_FLEA, NPC_PULP, NPC_PULP_FAMILY, NPC_SHERMA, NPC_SPECIALSHERMA, NPC_END };

enum class COLLISION_TYPE { COL_TOP, COL_BOTTOM, COL_LEFT, COL_RIGHT};

enum class KEY {
	NUM_0, NUM_1, NUM_2, NUM_3, NUM_4, NUM_5, NUM_6, NUM_7, NUM_8, NUM_9,
	Q, W, E, R, T, Y, U, I, O, P,
	A, S, D, F, G, H, J, K, L,
	Z, X, C, V, B, N, M,
	
	F1, F2, F3, F4, F5, F6, F7, F8, F9, F10,
	ARROW_UP, ARROW_DOWN, ARROW_LEFT, ARROW_RIGHT,
	LSHIFT, RSHIFT, LCTRL, RCTRL, ALT, ESCAPE, SPACE, RETURN,
	LBUTTON, RBUTTON, LAST
};
enum class KEY_STATE { DOWN, HOLD, UP, NONE };

enum class ITEM_TYPE { ITEM_USABLE, ITEM_DEFAULT, ITEM_WEAPON, ITEM_SHIELD, ITEM_UTIL, ITEM_END };

enum class BOSS_STATE		{	BOSS_START, BOSS_FURY, BOSS_STUN, BOSS_STOP, BOSS_NUCKBACK, BOSS_DEAD, BOSS_RDTT, BOSS_DOWN, BOSS_NONE	};

enum class BOSS_SKILL_STATE {	BOSS_DASH, BOSS_SPIN, BOSS_SPLIT, BOSS_LAND, BOSS_POKE, BOSS_PRNG, BOSS_PATK, BOSS_ASLH, BOSS_ASLH_BF, BOSS_ASLH_AF
							, BOSS_READY, BOSS_NONE		};
enum class MONSTER_STATE	{ MONSTER_IDLE_R, MONSTER_IDLE_L, MONSTER_WALK_R, MONSTER_WALK_L, MONSTER_ATTACK_R, MONSTER_ATTACK_L, 
								MONSTER_DEAD_R, MONSTER_DEAD_L, MONSTER_NONE};

enum class CHANNELID { SOUND_BGM, SOUND_EFFECT, SOUND_WEAPON, SOUND_PLAYER, SOUND_PLAYERWP, SOUND_PLAYERSTATE ,SOUND_MONSTER_CONVOY, SOUND_MONSTER_CHAMBER, SOUND_BOSS, MAXCHANNEL };